### ISSUE TITLE
"python manage.py check" produced zero errors but "python manage.py migrate" does

### ISSUE THREAD

**Issue by dkdndes** [sqlanywhere/sqlany-django#10]
I tested it with the following [example](https://github.com/dkdndes/sqlany-django/tree/master/example) and it generate the following error: "django.db.utils.OperationalError: Item 'django_session' already exists" but its the first time I run the following command:

    python manage.py migrate

Operations to perform:
  Synchronize unmigrated apps: staticfiles, messages
  Apply all migrations: admin, contenttypes, auth, sessions
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying sessions.0001_initial...Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/peterrosemann/Documents/Python/sqlany-django/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line

[...]

File "/Users/peterrosemann/Documents/Python/sqlany-django/env/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/peterrosemann/Documents/Python/sqlany-django/env/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/Users/peterrosemann/Documents/Python/sqlany-django/env/lib/python2.7/site-packages/sqlany_django-1.11-py2.7.egg/sqlany_django/base.py", line 98, in execute
  File "/Users/peterrosemann/Documents/Python/sqlany-django/env/lib/python2.7/site-packages/sqlanydb-1.0.6.1-py2.7.egg/sqlanydb.py", line 759, in execute
  File "/Users/peterrosemann/Documents/Python/sqlany-django/env/lib/python2.7/site-packages/sqlanydb-1.0.6.1-py2.7.egg/sqlanydb.py", line 736, in executemany
  File "/Users/peterrosemann/Documents/Python/sqlany-django/env/lib/python2.7/site-packages/sqlanydb-1.0.6.1-py2.7.egg/sqlanydb.py", line 658, in handleerror
  File "/Users/peterrosemann/Documents/Python/sqlany-django/env/lib/python2.7/site-packages/sqlanydb-1.0.6.1-py2.7.egg/sqlanydb.py", line 350, in standardErrorHandler

django.db.utils.OperationalError: Item 'django_session' already exists

    python manage.py check 

produced zero errors

**Comment by gperrow-SAP** [comment]
I cannot see the example you've linked to. When I click it, I get a 404.

**Comment by dkdndes** [comment]
https://github.com/dkdndes/sqlany-django/tree/master/example - sorry, was a typo. I updated the link

**Comment by gperrow-SAP** [comment]
Are you running both manage.py syncdb *and* manage.py migrate? You don't need to run syncdb - migrate does it for you.

**Comment by dkdndes** [comment]
see above: 
    python manage.py migrate

**Comment by gperrow-SAP** [comment]
I cannot reproduce this problem. In my case, running "python manage.py check" displays no errors, and "python manage.py migrate" also succeeds. However if I try to run "python manage.py migrate" a second time on the same database, I see the error you're getting. Make sure you're starting with a clean database.

**Comment by dkdndes** [comment]
Hi. I create the database without any django tables before I run the command. What happens if you try add the blog model from the webpage? Neither way, the error should not be there first or second time. Do you have any idea why it happens?

**Comment by gperrow-SAP** [comment]
No, but the Django docs say that you should be able to run "python manage.py migrate" twice and the second time will do nothing. That's not happening for me so perhaps there's something Django is expecting the driver to do that we're not doing. I will continue investigating.

**Comment by dkdndes** [comment]
Thank you!

**Comment by gperrow-SAP** [comment]
Version 1.12 fixes this problem. Autocommit is the default in Django 1.6, but in certain cases we were not enabling Autocommit. This would mean that things would get inserted or updated in the database during the migrate and then rolled back when the connection closed. We now enable autocommit on all connections for Django 1.6+.

**Comment by dkdndes** [comment]
Thank you! Will try it out later today!

**Comment by dkdndes** [comment]
Works prefect! Thank you.
