### ISSUE TITLE
Error when i go to admin page

### ISSUE THREAD

**Issue by AntoniRomera** [sqlanywhere/sqlany-django#14]
Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "C:\Users\aromera\Desktop\TAB25~1.MPR\proyecto\entornos\ETASKM~1\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "C:\Users\aromera\Desktop\TAB25~1.MPR\proyecto\entornos\ETASKM~1\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\aromera\Desktop\TAB25~1.MPR\proyecto\entornos\ETASKM~1\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\aromera\Desktop\TAB25~1.MPR\proyecto\entornos\ETASKM~1\lib\site-packages\django\views\decorators\cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\aromera\Desktop\TAB25~1.MPR\proyecto\entornos\ETASKM~1\lib\site-packages\django\contrib\admin\sites.py", line 377, in login
    return login(request, **defaults)
  File "C:\Users\aromera\Desktop\TAB25~1.MPR\proyecto\entornos\ETASKM~1\lib\site-packages\django\contrib\auth\views.py", line 47, in inner
    return func(*args, **kwargs)
  File "C:\Users\aromera\Desktop\TAB25~1.MPR\proyecto\entornos\ETASKM~1\lib\site-packages\django\views\decorators\debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "C:\Users\aromera\Desktop\TAB25~1.MPR\proyecto\entornos\ETASKM~1\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\aromera\Desktop\TAB25~1.MPR\proyecto\entornos\ETASKM~1\lib\site-packages\django\views\decorators\cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\aromera\Desktop\TAB25~1.MPR\proyecto\entornos\ETASKM~1\lib\site-packages\django\contrib\auth\views.py", line 82, in login
    auth_login(request, form.get_user())
  File "C:\Users\aromera\Desktop\TAB25~1.MPR\proyecto\entornos\ETASKM~1\lib\site-packages\django\contrib\auth\__init__.py", line 109, in login
    request.session.cycle_key()
  File "C:\Users\aromera\Desktop\TAB25~1.MPR\proyecto\entornos\ETASKM~1\lib\site-packages\django\contrib\sessions\backends\base.py", line 311, in cycle_key
    self.create()
  File "C:\Users\aromera\Desktop\TAB25~1.MPR\proyecto\entornos\ETASKM~1\lib\site-packages\django\contrib\sessions\backends\db.py", line 54, in create
    self.save(must_create=True)
  File "C:\Users\aromera\Desktop\TAB25~1.MPR\proyecto\entornos\ETASKM~1\lib\site-packages\django\contrib\sessions\backends\db.py", line 87, in save
    obj.save(force_insert=must_create, force_update=not must_create, using=using)
  File "C:\Users\aromera\Desktop\TAB25~1.MPR\proyecto\entornos\ETASKM~1\lib\site-packages\django\db\models\base.py", line 796, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\Users\aromera\Desktop\TAB25~1.MPR\proyecto\entornos\ETASKM~1\lib\site-packages\django\db\models\base.py", line 824, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "C:\Users\aromera\Desktop\TAB25~1.MPR\proyecto\entornos\ETASKM~1\lib\site-packages\django\db\models\base.py", line 908, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "C:\Users\aromera\Desktop\TAB25~1.MPR\proyecto\entornos\ETASKM~1\lib\site-packages\django\db\models\base.py", line 947, in _do_insert
    using=using, raw=raw)
  File "C:\Users\aromera\Desktop\TAB25~1.MPR\proyecto\entornos\ETASKM~1\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\aromera\Desktop\TAB25~1.MPR\proyecto\entornos\ETASKM~1\lib\site-packages\django\db\models\query.py", line 1043, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "C:\Users\aromera\Desktop\TAB25~1.MPR\proyecto\entornos\ETASKM~1\lib\site-packages\django\db\models\sql\compiler.py", line 1053, in execute_sql
    for sql, params in self.as_sql():
  File "C:\Users\aromera\Desktop\TAB25~1.MPR\proyecto\entornos\ETASKM~1\lib\site-packages\django\db\models\sql\compiler.py", line 1038, in as_sql
    result.append(self.connection.ops.bulk_insert_sql(fields, placeholder_rows))
  File "C:\Users\aromera\Desktop\TAB25~1.MPR\proyecto\entornos\ETASKM~1\lib\site-packages\sqlany_django\base.py", line 189, in bulk_insert_sql
    return "VALUES " + ", ".join([items_sql] * num_values)
TypeError: can't multiply sequence by non-int of type 'tuple'

Any idea?

**Comment by gperrow-SAP** [comment]
This looks like it's due to an undocumented change made in Django 1.9. The sqlany-django driver doesn't support Django 1.9 and up as of yet but I will see if I can get that support added.
