### ISSUE TITLE
Django 1.11 Support

### ISSUE THREAD

**Issue by matthewbest** [sqlanywhere/sqlany-django#17]
I followed the instructions for setting up a Django project with SQL Anywhere, but when I try to run `python3 manage.py syncdb`, or any other `manage.py` command for that matter, I get the following error:

`django.core.exceptions.ImproperlyConfigured: 'sqlany-django' isn't an available database backend.`

**Full Traceback**
`Traceback (most recent call last):
  File "/home/matthewbest/TEST/tutorial-env/lib/python3.5/site-packages/django/db/utils.py", line 111, in load_backend
    return import_module('%s.base' % backend_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 944, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'sqlany-django'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/matthewbest/TEST/tutorial-env/lib/python3.5/site-packages/django/core/management/__init__.py", line 351, in execute_from_command_line
    utility.execute()
  File "/home/matthewbest/TEST/tutorial-env/lib/python3.5/site-packages/django/core/management/__init__.py", line 325, in execute
    django.setup()
  File "/home/matthewbest/TEST/tutorial-env/lib/python3.5/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/matthewbest/TEST/tutorial-env/lib/python3.5/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/matthewbest/TEST/tutorial-env/lib/python3.5/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/matthewbest/TEST/tutorial-env/lib/python3.5/site-packages/django/contrib/auth/models.py", line 41, in <module>
    class Permission(models.Model):
  File "/home/matthewbest/TEST/tutorial-env/lib/python3.5/site-packages/django/db/models/base.py", line 139, in __new__
    new_class.add_to_class('_meta', Options(meta, **kwargs))
  File "/home/matthewbest/TEST/tutorial-env/lib/python3.5/site-packages/django/db/models/base.py", line 324, in add_to_class
    value.contribute_to_class(cls, name)
  File "/home/matthewbest/TEST/tutorial-env/lib/python3.5/site-packages/django/db/models/options.py", line 250, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/home/matthewbest/TEST/tutorial-env/lib/python3.5/site-packages/django/db/__init__.py", line 36, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/home/matthewbest/TEST/tutorial-env/lib/python3.5/site-packages/django/db/utils.py", line 240, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/home/matthewbest/TEST/tutorial-env/lib/python3.5/site-packages/django/db/utils.py", line 129, in load_backend
    raise ImproperlyConfigured(error_msg)
django.core.exceptions.ImproperlyConfigured: 'sqlany-django' isn't an available database backend.
Try using 'django.db.backends.XXX', where XXX is one of:
    'base', 'mysql', 'oracle', 'postgresql_psycopg2', 'sqlite3'
Error was: No module named 'sqlany-django'`

**Python Environment**
Django (1.8.5)
pip (9.0.3)
pkg-resources (0.0.0)
setuptools (39.0.1)
sqlany-django (1.13)
sqlanydb (1.0.9)

I'm using a virtual environment since my usual Django version is 1.11.

**Comment by matthewbest** [comment]
Please ignore the original post. I found the typo (`sqlany-django` vice `sqlany_django`) that was causing the error. However, when I was testing https://github.com/WaYdotNET/sqlany-django, I noticed that there are several errors that occur whenever I try to use manage.py migrate with Python 3.5. These errors occur on Django versions 1.9.x and 1.11.x.

We would love to make use of this product, but really need support for more modern Django versions.

**Comment by bittner** [comment]
Are there any plans to support a recent version of Django?
