### ISSUE TITLE
Django 1.8.5 Issue

### ISSUE THREAD

**Issue by JonahJ** [sqlanywhere/sqlany-django#6]
Can't get this working with the newest version of django... Debugging. Curious because `import sqlanydb` works fine.

```
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x03A05AE0>
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\django-1.8.5-py3.4.egg\django\db\utils.py", line 111, in load_backend
    return import_module('%s.base' % backend_name)
  File "C:\Python34\lib\importlib\__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\sqlany_django-1.9-py3.4.egg\sqlany_django\base.py", line 24, in <module>
  File "C:\Python34\lib\site-packages\sqlany_django-1.9-py3.4.egg\sqlany_django\client.py", line 1, in <module>
ImportError: cannot import name 'BaseDatabaseClient'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\django-1.8.5-py3.4.egg\django\utils\autoreload.py", line 229, in wrapper
    fn(*args, **kwargs)
  File "C:\Python34\lib\site-packages\django-1.8.5-py3.4.egg\django\core\management\commands\runserver.py", line 107, in inner_run
    autoreload.raise_last_exception()
  File "C:\Python34\lib\site-packages\django-1.8.5-py3.4.egg\django\utils\autoreload.py", line 252, in raise_last_exception
    six.reraise(*_exception)
  File "C:\Python34\lib\site-packages\django-1.8.5-py3.4.egg\django\utils\six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "C:\Python34\lib\site-packages\django-1.8.5-py3.4.egg\django\utils\autoreload.py", line 229, in wrapper
    fn(*args, **kwargs)
  File "C:\Python34\lib\site-packages\django-1.8.5-py3.4.egg\django\__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Python34\lib\site-packages\django-1.8.5-py3.4.egg\django\apps\registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "C:\Python34\lib\site-packages\django-1.8.5-py3.4.egg\django\apps\config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Python34\lib\importlib\__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "C:\Python34\lib\site-packages\django-1.8.5-py3.4.egg\django\contrib\auth\models.py", line 41, in <module>
    class Permission(models.Model):
  File "C:\Python34\lib\site-packages\django-1.8.5-py3.4.egg\django\db\models\base.py", line 139, in __new__
    new_class.add_to_class('_meta', Options(meta, **kwargs))
  File "C:\Python34\lib\site-packages\django-1.8.5-py3.4.egg\django\db\models\base.py", line 324, in add_to_class
    value.contribute_to_class(cls, name)
  File "C:\Python34\lib\site-packages\django-1.8.5-py3.4.egg\django\db\models\options.py", line 250, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "C:\Python34\lib\site-packages\django-1.8.5-py3.4.egg\django\db\__init__.py", line 36, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "C:\Python34\lib\site-packages\django-1.8.5-py3.4.egg\django\db\utils.py", line 240, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "C:\Python34\lib\site-packages\django-1.8.5-py3.4.egg\django\db\utils.py", line 129, in load_backend
    raise ImproperlyConfigured(error_msg)
django.core.exceptions.ImproperlyConfigured: 'sqlany_django' isn't an available
database backend.
Try using 'django.db.backends.XXX', where XXX is one of:
    'base', 'mysql', 'oracle', 'postgresql_psycopg2', 'sqlite3'
```

**Comment by gperrow-SAP** [comment]
Django 1.8.x is not supported by the SQL Anywhere driver. I will investigate adding support.

**Comment by dkdndes** [comment]
Any update?

**Comment by gperrow-SAP** [comment]
Upgrading the driver is on our list and we will release the new driver once it's ready but I'm afraid I don't have an ETA.

**Comment by dkdndes** [comment]
I started to add required changes in a fork.

**Comment by gperrow-SAP** [comment]
Version 1.11 of the driver was just uploaded, which includes support for Django 1.8.
