### ISSUE TITLE
Updates for django 1.8.5 generate error

### ISSUE THREAD

**Issue by dkdndes** [sqlanywhere/sqlany-django#8]
Hi, 

in my [fork](https://github.com/dkdndes/sqlany-django) I added changes required by Django 1.8.5+ but somehow I still struggle now with the following error message? 

    [...]
    File "/Users/peterrosemann/Documents/Python/dbanywhere/env/lib/python2.7/site-packages/django/db/__init__.py", line 36, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
    File "/Users/peterrosemann/Documents/Python/dbanywhere/env/lib/python2.7/site-packages/django/db/utils.py", line 240, in __getitem__
    backend = load_backend(db['ENGINE'])
    File "/Users/peterrosemann/Documents/Python/dbanywhere/env/lib/python2.7/site-packages/django/db/utils.py", line 129, in load_backend
    raise ImproperlyConfigured(error_msg)
    django.core.exceptions.ImproperlyConfigured: 'sqlany_django' isn't an available database backend.
    Try using 'django.db.backends.XXX', where XXX is one of: u'base', u'mysql', u'oracle', u'postgresql_psycopg2', u'sqlite3'
    Error was: No module named creation

Have you seen that before and could help?

**Comment by gperrow-SAP** [comment]
In the creation.py file, you need to change the import from django.db.backends.creation for version 1.8. Replacing that line with the following code will fix this problem:

    if djangoVersion[:2] >= (1, 8):
       from django.db.backends.base.creation import BaseDatabaseCreation, TEST_DATABASE_PREFIX
    else:
       from django.db.backends.creation import BaseDatabaseCreation, TEST_DATABASE_PREFIX

**Comment by gperrow-SAP** [comment]
Version 1.11 of the driver was just uploaded, which includes support for Django 1.8.

**Comment by dkdndes** [comment]
I tested it with the following [example](https://github.com/dkdndes/sqlany-django/example) and it generate the following error: "django.db.utils.OperationalError: Item 'django_session' already exists" but its the first time I run the following command:

    python manage.py migrate

Operations to perform:
  Synchronize unmigrated apps: staticfiles, messages
  Apply all migrations: admin, contenttypes, auth, sessions
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying sessions.0001_initial...Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/peterrosemann/Documents/Python/sqlany-django/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line

[...]

File "/Users/peterrosemann/Documents/Python/sqlany-django/env/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/peterrosemann/Documents/Python/sqlany-django/env/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/Users/peterrosemann/Documents/Python/sqlany-django/env/lib/python2.7/site-packages/sqlany_django-1.11-py2.7.egg/sqlany_django/base.py", line 98, in execute
  File "/Users/peterrosemann/Documents/Python/sqlany-django/env/lib/python2.7/site-packages/sqlanydb-1.0.6.1-py2.7.egg/sqlanydb.py", line 759, in execute
  File "/Users/peterrosemann/Documents/Python/sqlany-django/env/lib/python2.7/site-packages/sqlanydb-1.0.6.1-py2.7.egg/sqlanydb.py", line 736, in executemany
  File "/Users/peterrosemann/Documents/Python/sqlany-django/env/lib/python2.7/site-packages/sqlanydb-1.0.6.1-py2.7.egg/sqlanydb.py", line 658, in handleerror
  File "/Users/peterrosemann/Documents/Python/sqlany-django/env/lib/python2.7/site-packages/sqlanydb-1.0.6.1-py2.7.egg/sqlanydb.py", line 350, in standardErrorHandler

django.db.utils.OperationalError: Item 'django_session' already exists

    python manage.py check 

produced zero errors
